# Generated by Django 4.0.4 on 2022-05-27 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('rank', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('', 'Default')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('rank', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('', 'Default')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('rank', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('', 'Default')], max_length=300)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('labels', models.CharField(blank=True, choices=[('offer', 'Offer'), ('new', 'New'), ('hot', 'Hot'), ('', 'Default')], max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subcategory')),
            ],
        ),
    ]
