# Generated by Django 4.0.4 on 2022-06-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('', 'Default')], max_length=300),
        ),
    ]
